name: CI Pipeline - Validation & Security

on:
  push:
    paths:
      - "k8s-manifests/**"
      - "terraform/**"

jobs:
  # --- JOB 1: Kiểm tra lỗi cú pháp YAML (Bạn đã làm) ---
  validate-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Kubeconform Validation
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          args: "-summary -output json k8s-manifests/"

  # --- JOB 2: Quét bảo mật Terraform IaC (TASK 5) ---
  security-scan-iac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkov Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          soft_fail: true
