apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    # Trỏ thẳng đến kho chứa Helm Chart chính thức của cộng đồng Prometheus
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 57.0.0 # Sử dụng phiên bản ổn định
  destination:
    # Cài đặt trực tiếp lên cụm EKS hiện tại
    server: 'https://kubernetes.default.svc'
    namespace: monitoring # Tách biệt hệ thống giám sát ra một khu vực riêng
  syncPolicy:
    automated:
      prune: true
      selfHeal: true # ArgoCD sẽ tự sửa nếu ai đó lỡ tay xóa cấu hình giám sát
    syncOptions:
      - CreateNamespace=true # Tự động tạo namespace 'monitoring' nếu chưa có
