apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-monitoring-stack
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 57.0.0
    helm:
      values: |
        alertmanager:
          alertmanagerSpec:
            secrets:
              - telegram-secret
          
          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ['namespace', 'alertname']
              group_wait: 10s
              group_interval: 5m
              repeat_interval: 1h
              receiver: 'telegram-bot'
            receivers:
              - name: 'telegram-bot'
                telegram_configs:
                  - chat_id: 5959085245
                    bot_token_file: '/etc/alertmanager/secrets/telegram-secret/bot_token'
                    send_resolved: true
                    parse_mode: HTML
                    message: |-
                      🚨 <b>CẢNH BÁO TỪ KUBERNETES EKS</b> 🚨
                      <b>Tên:</b> {{ .GroupLabels.alertname }}
                      <b>Mô tả:</b> {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}

        additionalPrometheusRulesMap:
          custom-alerts:
            groups:
            - name: node-alerts
              rules:
              - alert: HighMemoryUsage
                expr: (100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)) > 90
                for: 2m
                labels:
                  severity: critical
                annotations:
                  summary: "RAM của máy chủ {{ $labels.instance }} đã vượt quá 90%!"
              
              - alert: HighCPUUsage
                expr: (100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 90
                for: 2m
                labels:
                  severity: critical
                annotations:
                  summary: "CPU của máy chủ {{ $labels.instance }} đã vượt quá 90%!"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
