apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount-service
  template:
    metadata:
      labels:
        app: discount-service
    spec:
      containers:
      - name: server
        image: discount-service:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: discount-service
spec:
  type: ClusterIP
  selector:
    app: discount-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
