name: CI Pipeline - Validation & Security

on:
  push:
    branches:
      - main

jobs:
  validate-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Đã đổi sang v4 để hết cảnh báo vàng

      - name: Kubeconform Validation
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          # Thêm cờ ignore-missing-schemas để nó tha cho file ArgoCD
          args: "-ignore-missing-schemas -summary -output json k8s-manifests/"

  security-scan-iac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Đã đổi sang v4 để hết cảnh báo vàng

      - name: Checkov Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          soft_fail: true
